### ISSUE TITLE
[Bug] Release v0.7.1 not availvable on grafana portal and so through grafana-cli

### ISSUE THREAD

**Issue by daloulou** [yesoreyeram/grafana-infinity-datasource#100]
Hi,

I found out that the last release of your plugin is not available on grafana.com and so through grafana-cli. Does it possible to upload it ?

Thanks,

Regards,

Azoulay Dan

**Comment by yesoreyeram** [comment]
Sure. There is a review and approval process there. So expect some delay.. Meantime if you want you can use latest version from https://github.com/yesoreyeram/grafana-infinity-datasource/releases
