### ISSUE TITLE
[Bug] Not able to handle too much data

### ISSUE THREAD

**Issue by Na-ru-to4170** [yesoreyeram/grafana-infinity-datasource#101]
**Describe the bug**
We have an endpoint which has approx 5-10M entries and when we request then it is getting timed out

**Screenshots**
Getting 502 bad gateway timeout 

**Version Details:**

- Grafana version : Latest
- Plugin version : v0.7.4

**Additional context**
Can't we implement something like pagination like splunk provide or is there a way?

**Comment by Na-ru-to4170** [comment]
@yesoreyeram

**Comment by yesoreyeram** [comment]
Pagnination is definitely not something we want to add plugin level. That is a feature request for Grafana itself. BTW, i don't think pulling 10M entries to brower is a good idea.

**Comment by yesoreyeram** [comment]
BTW, I don't think this is a bug with the plugin. Feel free to reopen if you think so.

**Comment by Na-ru-to4170** [comment]
Agree with that. @yesoreyeram 
Do you have any other which we can look to achieve this ?

**Comment by njohnstone2** [comment]
@yesoreyeram are you aware of any workaround solutions to handle pagination with the Infinity plugin? 

I am using an API that limits results to 100 items before enforcing pagination. It would be awesome if your plugin could support this as i am currently limited to ~12hrs worth of data which really limits the usability of my dashboard.
