### ISSUE TITLE
[Bug] Unsigned community plugin

### ISSUE THREAD

**Issue by gm7y8** [yesoreyeram/grafana-infinity-datasource#103]
the plugin is failing to load as it's not signed under the community

"Failed to load plugin" logger=plugins error="plugin \"yesoreyeram-infinity-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/grafana-infinity-datasource-0.7.5/src
**Screenshots**

**Version Details:**

- Grafana version :
- Plugin version :

**Additional context**
https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/

**Comment by yesoreyeram** [comment]
Hope you are downloading and loading from the published versions. Either from within releases or from grafana plugins page. They are already signed. 

If you are building plugin from source, you may not get the signature. 

More details appreciated how u download and install the plugin.

**Comment by gm7y8** [comment]
@yesoreyeram  it tried downloading from the git hub release page.. let me try from grafana official site

**Comment by yesoreyeram** [comment]
Are you using the correct github download URL ? https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.5/yesoreyeram-infinity-datasource-0.7.5.zip
