### ISSUE TITLE
Can I use this with api which is having headers 

### ISSUE THREAD

**Issue by hpatil47** [yesoreyeram/grafana-infinity-datasource#11]
Can I use this with api which is having headers. if yes how to do that

**Comment by yesoreyeram** [comment]
Yes you can. When setting up the datasoruce, select advanced and then specify headers there. 

The limitation is you will be tied with one domain. If you are targetting multi domain, you need to have individual datasources for each.

**Comment by hpatil47** [comment]
I am using JSON rest api to fetch the JSON data which is having custom headers, how to use those custom headers for that
