### ISSUE TITLE
[Bug] Dataframes returned by the plugin doesn't include refId

### ISSUE THREAD

**Issue by gdiana** [yesoreyeram/grafana-infinity-datasource#116]
**### Grafana v8.0.6 (68fe9e3431)**

**Describe the bug**

When using any data source, including the infinity data, for any panel queries and when using multiple query's it is noted that when trying to use the Panel Transform, **"Filter data by query"** that the Query Name (A,B or whatever) does not appear as a Series refID.

Below is what one should expect taken from the Grafana Documentation

![image](https://user-images.githubusercontent.com/13445152/128598087-e4e11107-85b4-4c73-8d8c-f3baa05fb555.png)

The same should apply whether oses a shared query or Global Query, if I am not mistaken?

So below is an example where I have used a query and just for debugging named it **GGGGGGG** as shown below

![image](https://user-images.githubusercontent.com/13445152/128598266-61d9d50d-0f00-40c2-8828-ed628a8727ab.png)

As may be seen the query name appears in the panel JSON DataFrame structure as **"name": "GGGGGGG",** as it can not find any reference to the Series refId as shown below even though at points RefId appears.

![image](https://user-images.githubusercontent.com/13445152/128598332-2f81c93d-105d-4a8d-a36d-5cbc3926b073.png)

As noted if  GGGGGGG was labelled as refId "GGGGGGG" I think this resolve the issue.

This is not new and I include the following link which demonstrates the issue

https://user-images.githubusercontent.com/30407135/96583031-6a45da80-12dc-11eb-82d7-79044840a28b.gif

It appears when doing any query the query name but be parsed as refID failing which one may not use other panel or Global Query's 

I also came across another bug in Variables, but note that this BUG is already noted, but not yet attended to.

**Comment by yesoreyeram** [comment]
Thanks @gdiana for reporting. I am aware of this issue and slliped from previous releases. Should be an easy fix.  Will do it in next release.

**Comment by gdiana** [comment]
Hi,

Noted thanks. And hopefully the variable query bug is also easily resolved.

Kind regards


Gregory Diana
_______________________________________


22 Glen Grove
Glenwood
Durban 4001

Phone(h&w):031-2616761 (h)
*Fax2Email: 086 474 3450*
Cell: 0784515277
E-mail: ***@***.***
E-mail: ***@***.*** ***@***.***>
Skype: gregory.diana
Print: ***@***.***

**Comment by yesoreyeram** [comment]
It seems the fix I had in my mind doesn't seems to work. I think this may require fix in grafana. 

I am able to put a local fix without touching grafana. But that does break existing dashboards unfortunately. Let me figure out what best I can do without breaking existing queries.

**Comment by gdiana** [comment]
Hi,
Noted and thanks, much appreciated.

Life is never simple!

**Comment by yesoreyeram** [comment]
I think this is solved now with recent infinity version.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/153843/164213380-8469f0e2-b6ce-45ed-bd63-e779bde05809.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/153843/164213408-06f10ec9-215e-4d1c-9cce-c30920ec2aa3.png">

@gdiana - Is this still an issue for you?

**Comment by gdiana** [comment]
Yes, it appears to be working fine now as shown below.

![image](https://user-images.githubusercontent.com/13445152/164218259-fe6cb315-6e83-4cd0-b6e3-58ad4cf9d701.png)

Just a note that if one changes the Query Name for say A to QUERY1 then one must do a panel refresh for the new name to be parsed as the new query ref Id in the Transform.

Many thanks

**Comment by yesoreyeram** [comment]
> Just a note that if one changes the Query Name for say A to QUERY1 then one must do a panel refresh for the new name to be parsed as the new query ref Id in the Transform.

thanks @gdiana for the hint and confirming. I think thats the desired behaviour.
