### ISSUE TITLE
I am using JSON rest api to fetch the JSON data which is having custom headers, how to use those custom headers for that

### ISSUE THREAD

**Issue by hpatil47** [yesoreyeram/grafana-infinity-datasource#12]
I am using JSON rest api to fetch the JSON data which is having custom headers, how to use those custom headers for that

**Comment by jokerfvd** [comment]
Leave an example of your JSON

**Comment by hpatil47** [comment]
Actually I am using JSON rest api which is having two custom headers, even if I have configured the headers in data sources, still I am getting the error like missing header while configuring the panel

**Comment by hpatil47** [comment]
Can any one help here ?

**Comment by yesoreyeram** [comment]
@hpatil47 what error you are getting? Have you checked the datasource configuration? any screenshots / logs would be helpful to understand the issue.

**Comment by hpatil47** [comment]
I am getting some missing headers error while configuring the json panel for json api.

**Comment by hpatil47** [comment]
I am using this URL https://api-docs.acloud.guru/ to configure as data source, I have configured the both the headers in data source, but while configuring the panel I am getting "missing x-consumer-id in header". can you please help on it.

**Comment by hpatil47** [comment]
Can you please help @yesoreyeram and @jokerfvd

**Comment by hpatil47** [comment]
Can you please help @yesoreyeram and @jokerfvd

**Comment by yesoreyeram** [comment]
Here is an example of using custom headers.

Datasource setup

![image](https://user-images.githubusercontent.com/153843/102995864-d978be80-4519-11eb-9673-3dc23c1afa28.png)

and in query editor

![image](https://user-images.githubusercontent.com/153843/102995934-0200b880-451a-11eb-992b-300948ab17db.png)

I confirm that the above setup works.
