### ISSUE TITLE
[Bug] 404 in Grafana Cloud

### ISSUE THREAD

**Issue by SurPaul** [yesoreyeram/grafana-infinity-datasource#120]
**Describe the bug**
I do everything according to the [wiki](https://sriramajeyam.com/grafana-infinity-datasource/wiki/json/), but for any request Grafana Cloud gives me a 404.

**Screenshots**
Wiki | My
--- | ---
![](https://user-images.githubusercontent.com/153843/108413678-34314c80-7223-11eb-9cce-603134ec2d48.png) | ![Снимок экрана от 2021-08-12 21-31-06](https://user-images.githubusercontent.com/1708881/129242016-fe916376-3334-4e9c-b7b2-4181eb175743.png)
![](https://user-images.githubusercontent.com/153843/108415043-de5da400-7224-11eb-9295-d49fcc18464a.png) | ![Снимок экрана от 2021-08-12 21-32-18](https://user-images.githubusercontent.com/1708881/129242175-862887d5-2856-4d37-90ab-409bc06458c3.png)

**Version Details:**

- Grafana version : Grafana v8.0.6 (68fe9e3431)
- Plugin version : 0.7.0

**Comment by yesoreyeram** [comment]
Did you leave the URL field in the datasource config empty? Try deleting the URL in the datasource config and try again.

**Comment by SurPaul** [comment]
> Did you leave the URL field in the datasource config empty? Try deleting the URL in the datasource config and try again.

I remember exactly that I removed the url. Now only deleting the source and creating a new one helped.

[https://youtu.be/vmf0Rk6D4JI](https://youtu.be/vmf0Rk6D4JI)

**Comment by yesoreyeram** [comment]
Sorry you had a trouble. Definitely seems to be bug while updating the datasource. I just added to my backlog to fix this.

Glad to see a fresh configuration helped.

**Comment by SurPaul** [comment]
> Sorry you had a trouble. Definitely seems to be bug while updating the datasource. I just added to my backlog to fix this.
> 
> Glad to see a fresh configuration helped.

Thank you!
