### ISSUE TITLE
[Bug] JSON without brackets don't generate Pie Chart

### ISSUE THREAD

**Issue by jokerfvd** [yesoreyeram/grafana-infinity-datasource#13]
**Describe the bug**
It's possible to generate a table from a JSON without brackets but it don't generate a Pie Chart

**Screenshots**
Creating a table from a JSON without brackets
![image](https://user-images.githubusercontent.com/2172117/101407390-97187600-38b9-11eb-9e72-2e5debc76028.png)

Creating a table from a JSON with brackets
![image](https://user-images.githubusercontent.com/2172117/101407572-da72e480-38b9-11eb-8588-207d88b873ef.png)

Creating a Pie Chart from a JSON with brackets
![image](https://user-images.githubusercontent.com/2172117/101407704-0aba8300-38ba-11eb-9d83-4532378969ef.png)

When a try to create a Pie Chart from a JSON without brackets appears the message "No data points"
![image](https://user-images.githubusercontent.com/2172117/101407944-64bb4880-38ba-11eb-9c3e-e1808e3a0f59.png)

**Version Details:**
 - Grafana version : 7.1.1
 - Plugin version : 0.6.0

**Comment by yesoreyeram** [comment]
Hi @jokerfvd - Sorry i don't understand the usecase. How do you do piechart from a single object? Don't you need array of values?

**Comment by jokerfvd** [comment]
I never said I wanted a single object. I just showed a single object with brackets working and without not working.
This JSON for example:

`{"Country":"USA", "TotalDeaths":5000},{"Country":"Brazil", "TotalDeaths":1000},{"Country":"Argentina", "TotalDeaths":2000}`

This JSON don't work because don't have brackets

**Comment by jokerfvd** [comment]
I saw the problem in the code.

It is not generated a timeseries when the JSON don't have brackets
In the JSONParser.ts

```
if (Array.isArray(jsonResponse)) {		
      this.constructTableData(jsonResponse);
      this.constructTimeSeriesData(jsonResponse, endTime);
    } else {
      this.constructSingleTableData(jsonResponse);
    }
```

**Comment by jokerfvd** [comment]
Here is an example of the JSON I wanted to use to create a pie chart

`{"Data":"2020-12-11T08:33:00-03:00","aaa":{"ggg":{"total":39280.02,"hhh":23543.6836,"ttt":6645.278,"eee":0.0,"nnn":1853.74365,"sss":282.251068,"bbb":2331.66016,"ccc":4623.40332},"ccc":40367.0078,"iii":4756.881,"eee":3669.89282},"sul":{"ggg":{"total":8908.193,"hhh":6213.518,"ttt":1882.29932,"eee":812.375732,"nnn":0.0,"sss":0.0},"ccc":14277.6592,"iii":5369.466,"eee":0.0}}`

**Comment by yesoreyeram** [comment]
```
{"Country":"USA", "TotalDeaths":5000},{"Country":"Brazil", "TotalDeaths":1000},{"Country":"Argentina", "TotalDeaths":2000}
```

I am seeing the above is not a valid json object.  Check the results here https://jsonlint.com/ . JSON should be single object or array of objects.

**Comment by jokerfvd** [comment]
According to https://jsonlint.com/

`{"Data":"2020-12-11T08:33:00-03:00","aaa":{"ggg":{"total":39280.02,"hhh":23543.6836,"ttt":6645.278,"eee":0.0,"nnn":1853.74365,"sss":282.251068,"bbb":2331.66016,"ccc":4623.40332},"ccc":40367.0078,"iii":4756.881,"eee":3669.89282},"sss":{"ggg":{"total":8908.193,"hhh":6213.518,"ttt":1882.29932,"eee":812.375732,"nnn":0.0,"sss":0.0},"ccc":14277.6592,"iii":5369.466,"eee":0.0}}`

Is a valid JSON and I can't generate a pie chart with it.

![image](https://user-images.githubusercontent.com/2172117/101938686-8bcb9000-3bc2-11eb-9d7a-ef06468e1959.png)


![image](https://user-images.githubusercontent.com/2172117/101938574-53c44d00-3bc2-11eb-84fb-26e9ac393a99.png)
