### ISSUE TITLE
[Bug] Can't convert figures with comma to number 

### ISSUE THREAD

**Issue by kkasavchenko** [yesoreyeram/grafana-infinity-datasource#140]
When querying a CSV that contains a number > 999 in the following format "1,234" and configuring a column as "Number", Grafana returns "NaN". 

Here is the sample CSV returned by an API query:
# Alerts
"1,378"

Infinity query configuration:
![image](https://user-images.githubusercontent.com/35329618/131340587-102dfc50-6155-412a-a171-02ed9b9c653c.png)

Grafana version : 8.1.1
Plugin version : 0.7.0

P.S. thanks a lot for the tool, saves really a lot of time for prototypes!

**Comment by yesoreyeram** [comment]
This is now fixed in version 0.8
