### ISSUE TITLE
[Bug]Issue for connection to a RESTAPI hosted on localhost

### ISSUE THREAD

**Issue by xccatana** [yesoreyeram/grafana-infinity-datasource#148]
**Describe the bug**
I have a local deployment with Grafana and infinity plugin. Everything is hosted in Docker.
I created a REST API server to serve some metrics to infinity plugin in Golang.
I start the server from localhost, then in infinity URL I paste the URL http://localhost:8080/count_alerts after setting up the datasource and checked TLS/SSL Settings - Skip TLS Verify.

When I use localhost I get a 500 server error when trying to reach my JSON data.
Message: error getting response from http://localhost:8080/count_alerts

When I use the IP for my host, I can get the proper JSON data.

- Grafana version : grafana:7.2.0
- Plugin version : 0.7.8

**Comment by yesoreyeram** [comment]
I think you need to give the container name instead of localhost in your URL as Grafana and your API will be running in different containers and the localhost is different for both.

you can confirm this by ssh into grafana's container. `docker exec -it YOUR_GRAFANA_CONTAINER_NAME bash` and then `curl http://localhost:8080/count_alerts` from there.

**Comment by xccatana** [comment]
The Go REST Api server is not inside the container, my bad, is running on my laptop on locahost and port: 8080.
If they were both inside containers I would have used what you said, is obvious.

**Comment by yesoreyeram** [comment]
Then you need to setup the docker network correctly to access the localhost as described here https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach#:~:text=Use%20%2D%2Dnetwork%3D%22host%22,for%20Linux%2C%20per%20the%20documentation.
