### ISSUE TITLE
[Bug] Config from query results transform does not work 

### ISSUE THREAD

**Issue by bgmastermind** [yesoreyeram/grafana-infinity-datasource#155]
**Describe the bug**
Config from query results transform does not work. Config query is not selectable

**Screenshots**
![image](https://user-images.githubusercontent.com/24807093/135599711-ea649ed2-8d2e-4029-9b5d-c9b882ec7003.png)
**Version Details:**

- Grafana version :
- v8.1.4 (6855cdff7c) - docker

- Plugin version :
0.7.8

**Additional context**
From some searches I found that probably refid is missing, and that's why config query is missing

**Comment by yesoreyeram** [comment]
v0.8.8 should have fixed this. Lets know if that not working for you.
