### ISSUE TITLE
[Bug] CSV numbers not follow panel's decimals setting

### ISSUE THREAD

**Issue by imReker** [yesoreyeram/grafana-infinity-datasource#168]
**Describe the bug**
Numbers are rounded incorrectly.

**Screenshots**
![1](https://user-images.githubusercontent.com/4949937/136653134-577fd5bd-7eb6-4043-af68-07e05c96485f.png)

**Version Details:**

- Grafana version : v8.1.2 (103f8fa094)
- Plugin version : 0.7.8

**Comment by yesoreyeram** [comment]
You don't have columns specified. So all the fields are considered as strings.
