### ISSUE TITLE
Plugin fails to start in kubernetes cluster. 

### ISSUE THREAD

**Issue by aurabhi** [yesoreyeram/grafana-infinity-datasource#197]
**Describe the bug**
When the plugin is included in grafana 7.5.9 running in kubernetes cluster the plugin fails with this below trace. 

t=2021-11-11T06:08:59+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=https subUrl=/grafana socket=
t=2021-11-11T06:08:59+0000 lvl=eror msg="plugin init error" logger=plugins.backend pluginId=yesoreyeram-infinity-datasource error="open /tmp/plugin412270376: read-only file system"
t=2021-11-11T06:08:59+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=yesoreyeram-infinity-datasource error="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply \n\n needs to be recompiled to support the latest protocol."

**Version Details:**

- Grafana version : 7.5.9
- Plugin version : latest

**Comment by yesoreyeram** [comment]
Can you provide more details on how to reproduce the issue? with plugin version, os version, how you are provisioning grafana, etc. Otherwise, I don't think I can reproduce this.
