### ISSUE TITLE
[Bug] No data points message when trying to create a pie chart from JSON

### ISSUE THREAD

**Issue by jokerfvd** [yesoreyeram/grafana-infinity-datasource#20]
**Describe the bug**
It's not possible to create a pie chart with the JSON showed in the images. But with the same JSON it's possible to create a table.

**Screenshots**

Table visualization working with the JSON
![image](https://user-images.githubusercontent.com/2172117/102786116-c0d3a180-437d-11eb-9048-087137456ed1.png)

Pie Chart visualization not working with the JSON
![image](https://user-images.githubusercontent.com/2172117/102786598-8c141a00-437e-11eb-8b10-70c1e2258442.png)

Pie Chart visualization works only if the JSON has []
![image](https://user-images.githubusercontent.com/2172117/102786765-c8477a80-437e-11eb-9615-22df283a7d4e.png)

**Version Details:**
 - Grafana version : 7.1.1
 - Plugin version : 0.6.0

**Additional context**
The JSON used

`{"Data":"2020-12-11T08:33:00-03:00","aaa":{"ggg":{"total":39280.02,"hhh":23543.6836,"ttt":6645.278,"eee":0.0,"nnn":1853.74365,"sss":282.251068,"bbb":2331.66016,"ccc":4623.40332},"ccc":40367.0078,"iii":4756.881,"eee":3669.89282},"sss":{"ggg":{"total":8908.193,"hhh":6213.518,"ttt":1882.29932,"eee":812.375732,"nnn":0.0,"sss":0.0},"ccc":14277.6592,"iii":5369.466,"eee":0.0}}`

The pie chart visualization only works when the JSON has brackets wich is not always necessary for having a valid JSON.
The showed JSON is valid as can be seen in [](https://jsonlint.com/)

**Comment by yesoreyeram** [comment]
Hi @jokerfvd  - sorry for the delay. probably you need `$.` as your root selector. Relevant document available [here](https://yesoreyeram.github.io/grafana-infinity-datasource/wiki/json.html#jsonpath-in-root-selector).

![image](https://user-images.githubusercontent.com/153843/107762101-67a44080-6d24-11eb-96ce-811862eb4744.png)

Make sure you have recent plugin package from releases https://github.com/yesoreyeram/grafana-infinity-datasource/releases. I am closing this now. If your issue exist, feel free to reopen.
