### ISSUE TITLE
[Bug] Plugin unavailable with Grafana 8.2.5

### ISSUE THREAD

**Issue by jykae** [yesoreyeram/grafana-infinity-datasource#203]
**Describe the bug**
Steps:
1: Installed plugin
2. added datasource
3. Save & Test => Plugin available

**Screenshots**
<img width="853" alt="Näyttökuva 2021-11-25 kello 11 28 35" src="https://user-images.githubusercontent.com/293452/143415434-fff67b90-0e4f-4ad3-84ed-c75be5a900b2.png">

**Version Details:**

- Grafana version : 8.2.5
- Plugin version : 0.7.8

**Comment by jykae** [comment]
@yesoreyeram How I can debug whats wrong in the backend ?

**Comment by yesoreyeram** [comment]
Did you check the grafana logs? Usually this occurs when plugin binaries installed incorrectly. ( If you have installed manually try`chmod +x` over the binaries ) Or do a fresh installation of the plugin from grafana.

I tried with 8.2.3 (https://grafana-infinity-datasource.herokuapp.com/) and it works for me. I guess 8.3.5 shouldn't have any issues as well but I will try later and confirm.

**Comment by jykae** [comment]
> Did you check the grafana logs? Usually this occurs when plugin binaries installed incorrectly. ( If you have installed manually try`chmod +x` over the binaries ) Or do a fresh installation of the plugin from grafana.

Tried reinstalling & chmod +x for binaries, did not help. I will crawl logs if I find any guidance there..

**Comment by jykae** [comment]
> I can confirm plugin works in 8.2.5 as well.

Yes, works on my macos but still confused why not on CentOS machine 🤷‍♂️

**Comment by jykae** [comment]
Got it working with GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource 🎉 

Thanks for updating that installation option @yesoreyeram

**Comment by yesoreyeram** [comment]
Glad to know that you sorted out. Sorry for the typical "It works on my machine" answer though.
