### ISSUE TITLE
Seems like Query Inspect does not work when trying to trouble shoot

### ISSUE THREAD

**Issue by sudhirpandey** [yesoreyeram/grafana-infinity-datasource#207]
**Describe the bug**
Trying to see what queries are actually fired upon, to see if variable values are correctly being used , but it seems the inspect Query button when clicked seems to load for ever.

**Screenshots**
![Screenshot 2021-12-02 at 10 30 36](https://user-images.githubusercontent.com/1481305/144395092-c9ff5cb5-04be-4158-8095-af5c37554778.png)
**Version Details:*

- Grafana version : 8.2.5
- Plugin version : 0.7.10

**Additional context**
Its reproducible here as well,  https://grafana-infinity-datasource.herokuapp.com/d/try/try?orgId=1&editPanel=2

**Comment by yesoreyeram** [comment]
That is one tradeoff we have now in the datasource to support dynamic data. Btw, you can open browser developer tools/F12 network tab to inspect the data as a workaround.

**Comment by sudhirpandey** [comment]
Hi ,
I have tried that already but network inspect tool , i dont see the variable expanded as well ,
for example my variable is  svc,

I have tried to use variable as
![Screenshot 2021-12-02 at 12 03 00](https://user-images.githubusercontent.com/1481305/144410426-488b6700-fc12-4f9b-8c85-3c31d057cf79.png)
and same varaible is passed in query params too
![Screenshot 2021-12-02 at 13 28 30](https://user-images.githubusercontent.com/1481305/144422086-630fa44c-38ea-4abc-9b88-2ba9ace9abe8.png)


and i am trying to use table visualization to view things , My variable is multi selection hence, i have enabled repeat option as 
![Screenshot 2021-12-02 at 12 02 42](https://user-images.githubusercontent.com/1481305/144410592-12c1c258-0ec0-4e67-a5a2-e784dba2fd70.png)

Now via developer tools trying to see what variables value was passed and how many times 
i can see multiple request was made according to the variable selection but the table panels genearted does not dispay any data , but the backend is sending data ..and i can see it in response, ( and its json response i am suppose to get as well as seen in screen shot below )

here two values are selected, but we see three request, and two panel generated shows no data 

![Screenshot 2021-12-02 at 12 54 36](https://user-images.githubusercontent.com/1481305/144421500-6d3c9490-784a-4975-af61-dc5ff69671f7.png)

and svc variable doesnot seem to be expanded, ( how ever the same variable under service query params is expanded)

![Screenshot 2021-12-02 at 12 55 03](https://user-images.githubusercontent.com/1481305/144421750-982a5025-2e33-47e8-84e2-7d1808d2b6f7.png)

and we also see we are getting data from backend

![Screenshot 2021-12-02 at 12 55 26](https://user-images.githubusercontent.com/1481305/144421903-2dbb65f1-6baf-4fcd-a75e-87ffd68ba1ce.png)


So all in all most of the things are working , but the repeated table panels doesnot show any data ( when multiple values is selected).

If single value is selected  everything works. Could it be issue with  how Rows/Root selection works with json, went repetation applied ?

**Comment by yesoreyeram** [comment]
Glad to know it worked for you. On the other side, I don't remember row/root support query variable yet.

**Comment by yesoreyeram** [comment]
It should work now in latest version of the plugin. 0.8.3
