### ISSUE TITLE
Infinity variable list from column not working

### ISSUE THREAD

**Issue by zapi7557** [yesoreyeram/grafana-infinity-datasource#208]
Hey,
What Am I doing wrong, trying to get variable list same as on infinity webpage example

![Screenshot_10](https://user-images.githubusercontent.com/26165632/145989309-2a840770-0520-4390-a782-1e31ddc3ad58.png)

all I get is none
without column showing all.
![Screenshot_11](https://user-images.githubusercontent.com/26165632/145989370-7a342d65-65c8-4788-8c14-800047eb085a.png)

Grafana v8.3.1
Infinity v0.7.8

**Comment by yesoreyeram** [comment]
Can you check with infinity [v0.8.0-dev.7](https://github.com/yesoreyeram/grafana-infinity-datasource/releases/tag/v0.8.0-dev.7) ?
That seems working for me in https://grafana-infinity-datasource.herokuapp.com/d/variables

**Comment by zapi7557** [comment]
Thanks Sriram, it's working now :)
