### ISSUE TITLE
Trying to filter columns in variable screen removes all data

### ISSUE THREAD

**Issue by Donal-Goggin** [yesoreyeram/grafana-infinity-datasource#209]
**Describe the bug**
Getting results on a infinity data source variable works only for the base URL. The results however come back without names, I'm not sure if that is by design. When I try to filter the column names then all values disappear. They vanish immediately after selecting the column option and also when I input the exact name of the field in the JSON. 

**Screenshots**
Screenshot with just the base URL and values visible below.
![image](https://user-images.githubusercontent.com/32106124/146224116-a885abd1-1557-4123-b0b5-4f0510b1a62e.png)

Column selector opened and valued removed
![image](https://user-images.githubusercontent.com/32106124/146224368-c6c6ed88-4f65-4f22-b289-5c6e993ba142.png)

Column specified and no values
![image](https://user-images.githubusercontent.com/32106124/146224606-c1cff61e-38f8-4f3a-931e-e2c96a39947a.png)

**Version Details:**

- Grafana version : 8.1.1
- Plugin version : 0.7.8

**Additional context**
These column options work perfectly fine when adding an infinity panel, it seems only the adding-as-a-variable route has issues.

**Comment by yesoreyeram** [comment]
Can you try plugin 0.8.0? It is in dev.. probably will release soon

**Comment by Donal-Goggin** [comment]
Thank you. I tried the test dash you have for this fix and it looks good but unfortunately we can't update until it's released. I see from other comments that there is a workaround by editing the JSON but I'm having trouble figuring out what edits are needed in it.

**Comment by yesoreyeram** [comment]
Closing this as 0.8.0 already released with bug fixes.
