### ISSUE TITLE
Zeroes in place of null values after update

### ISSUE THREAD

**Issue by zapi7557** [yesoreyeram/grafana-infinity-datasource#210]
Hey Sriram,
After I updated to newset ver. as in linked ticket https://github.com/yesoreyeram/grafana-infinity-datasource/issues/208
all my null values became automatically zeroes and showed up on the graph like below

![Screenshot_10](https://user-images.githubusercontent.com/26165632/146350323-7ef439ef-ff1d-40f7-acf8-8e6c9cbda195.png)

How can I overcome this, is there any option to handle null values?

**Comment by yesoreyeram** [comment]
I don't understand the issue. Can you give me a sample data and steps to reproduce? which version of grafana and plugin you are using? what you upgraded? grafana/plugin? Hard to tell what's going on without these details.

**Comment by zapi7557** [comment]
Grafana v8.3.1
Infinity v0.7.8  <- here I had no problems with those zeroes
Infinity v0.8.0-dev.7 <- problems started here after your instructions to update from this ticket https://github.com/yesoreyeram/grafana-infinity-datasource/issues/208

Sample data JSON
![Screenshot_11](https://user-images.githubusercontent.com/26165632/146364492-d9010614-daad-403c-8937-f75f15a89b9c.png)

[{"FinishDate":"2021-12-13","Closed":"40","Planned":"","Reserved":"17","Started":"44"},{"FinishDate":"2021-12-14","Closed":"48","Planned":"","Reserved":"33","Started":"30"},{"FinishDate":"2021-12-15","Closed":"74","Planned":"","Reserved":"7","Started":"52"},{"FinishDate":"2021-12-16","Closed":"27","Planned":"","Reserved":"","Started":"51"},{"FinishDate":"2021-12-17","Closed":"76","Planned":"","Reserved":"25","Started":"187"},{"FinishDate":"2021-12-20","Closed":"158","Planned":"","Reserved":"","Started":"53"},{"FinishDate":"2021-12-21","Closed":"54","Planned":"","Reserved":"","Started":"105"},{"FinishDate":"2021-12-22","Closed":"8","Planned":"11","Reserved":"237","Started":"21"},{"FinishDate":"2021-12-23","Closed":"","Planned":"","Reserved":"","Started":"15"}]

**Comment by yesoreyeram** [comment]
Thank you for the information. I will investigate and fix this in next release
