### ISSUE TITLE
Global Query Selects don't work 

### ISSUE THREAD

**Issue by youmms** [yesoreyeram/grafana-infinity-datasource#215]
**Describe the bug**
Install Infinity within Grafana. 
Add data source. 
Add global query
Edit global query: Select-Elements for Type, Source and Format do open/show options but options are not selectable. Thuas no changes are applicable.

**Screenshots**
[Screenshot (onetime link)](https://file.io/ZheYVRTmpocD)

**Version Details:**

- Grafana version : Grafana v8.3.3
- Plugin version : 0.7.10

**Additional context**
Windows 10 Professional
Chrome Version 96.0
Firefox 95.0

**Console output
There are no errors shown but one depreaction warning:
deprecationWarning.ts:14 [Deprecation warning] SelectBase: menuShouldPortal={false} is deprecated. Use menuShouldPortal={true} instead
j @ deprecationWarning.ts:14
R @ SelectBase.tsx:144
ri @ react-dom.production.min.js:157
Zs @ react-dom.production.min.js:267
Su @ react-dom.production.min.js:250
ku @ react-dom.production.min.js:250
wu @ react-dom.production.min.js:250
mu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Wo @ react-dom.production.min.js:122
Du @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
Au @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
M @ scheduler.production.min.js:16
_.port1.onmessage @ scheduler.production.min.js:12

**Comment by yesoreyeram** [comment]
have you tried v0.8.0 version? Feel free to reopen with reproduction steps if still the issue exists. Thank you.
