### ISSUE TITLE
CSV from raspberry pi + nginx source - "unexpected EOF" on Grafana dashboard refresh

### ISSUE THREAD

**Issue by Kybeer** [yesoreyeram/grafana-infinity-datasource#237]
Hello,

I have a fairly static small CSV file (it's being updated once/day, is 220KB, and has 5000 lines) residing on a a RaspberryPi Zero. The file is presented via an Nginx URL, and Infinity in Grafana is pointing to the file for data source. 

Now to my problem;

With just one panel of said CSV data in Grafana, the CSV file can be loaded and displayed correct. But as soon as I add a 2nd panel with the same CSV file, refreshes are very slow, and I get **"unexpected EOF" error message on the dashboards**. Sometimes I can refresh again, and they panels are ok. Sometimes they give unexpected EOF again. 

I interpret this as the file loading sometimes gets interrupted, generating the EOF error message. 

I have verified that **other CSV files behave exactly the same,** if they are hosted in exactly the same way (like this one https://sample-videos.com/csv/Sample-Spreadsheet-500000-rows.csv).

**Is there any way in the Infinity plugin. to limit the amount of simultaneous queries, in a dashboard.** Or perhaps that's more of a Grafana question...

I have multiple other data sources in the same Grafana (InfluxDB, Prometheus...) and they work as expected. 

To visualize:

With two panel I get EOF (it's the same panel, duplicated marked with red squares)

![image](https://user-images.githubusercontent.com/57593336/149821681-30a37d47-727a-446f-9ff3-72685ebf8da7.png)

Ok with just one panel (same data source / csv file and panel as above):

![image](https://user-images.githubusercontent.com/57593336/149821775-919e7841-998d-42da-b764-81518cd903a9.png)

If I click the EOF error ! icon:

![image](https://user-images.githubusercontent.com/57593336/149822015-5b05dc56-9efc-4e55-a823-bef7eab7764e.png)

_Originally posted by @Kybeer in https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/236_

**Comment by Kybeer** [comment]
I "solved" this problem by moving the HTTP endpoint / CSV file to a more performant device (Raspberry Pi 3). All query problems are gone now, so it was a strict performance issue.

**Comment by yesoreyeram** [comment]
Sorry for the delayed response and glad to know you figured it out.
