### ISSUE TITLE
Legacy query UnixTimeStamp() is not evaluated properly

### ISSUE THREAD

**Issue by marknorton-sabio** [yesoreyeram/grafana-infinity-datasource#238]
**Describe the bug**
Legacy query `UnixTimeStamp()` is not evaluated when used in panels or queries

**Screenshots**
Variable Definition
![Screenshot 2022-01-24 at 09 43 35](https://user-images.githubusercontent.com/95362420/150759502-bddd4e5b-2c18-4144-af43-0e54de4923f5.png)

Use in panel
![Screenshot 2022-01-24 at 09 47 47](https://user-images.githubusercontent.com/95362420/150759622-1d7b882b-7d05-4dbe-abc0-c2bbd8b30db2.png)

Output
![Screenshot 2022-01-24 at 09 44 24](https://user-images.githubusercontent.com/95362420/150759663-aee01d25-c7d1-480c-b8f4-6e9210266419.png)

**Version Details:**

- Grafana version : 8.3.3
- Plugin version : 0.8.0

**Additional context**
N/A

**Comment by yesoreyeram** [comment]
Right. I was able to reproduce this and fixing soon.

BTW, curious to know what is the usecase? Can't you use grafana's built-in variable `${to}` if you are looking for dashboard end time?

**Comment by marknorton-sabio** [comment]
Thanks for the quick fix. We're not looking for dashboard end time, we are needing client current time (and didn't want to have to extract it from the request).
