### ISSUE TITLE
[Bug] Variables of type Query partially broken

### ISSUE THREAD

**Issue by dastein1** [yesoreyeram/grafana-infinity-datasource#250]
**Describe the bug**
I noticed that on _main_ (d650aea) variable queries are not working. In the latest published version the JSON default example with queryType _Infinity_ populates the preview, on latest main it does not. Similarly when I try to do a GQL query there's no preview coming through (seems similar to #191).

- Grafana version : v8.3.4 (a551d74b11)
- Plugin version : HEAD

**Comment by yesoreyeram** [comment]
Thanks for reporting @dastein1 . It was a miss when migrating to backend query. I have the fix ready and will publish later.
