### ISSUE TITLE
[Bug] Error to use an api with api_token like parameter

### ISSUE THREAD

**Issue by pinou63** [yesoreyeram/grafana-infinity-datasource#263]
**Describe the bug**
I would like to use an api with this form:

https://******/api/v1/valeurs/mensuelle?api_token=TOKEN&sites=FR20062&date_debut=2021-01-01&label_court_polluant=PM10
I try to put all the parameters but i always have an expected error

It seems that the parameter api_token is not supported by the application

**Screenshots**

![image](https://user-images.githubusercontent.com/65943134/154437659-83132702-0458-4420-9990-b7ea574a984b.png)

**Version Details:**

- Grafana version : V8.3.6
- Plugin version :  0.8.0

**Additional context**

Thanks for all

Yann

**Comment by yesoreyeram** [comment]
Does this error occurs with any other API? what happens if you navigate the API directly from the browser?

**Comment by pinou63** [comment]
This error occurs with all the api i used with this form that's why, i think the problem come from the parameter api_token.
I have a good result when I navigate this api in a browser.

![image](https://user-images.githubusercontent.com/65943134/154443742-91071564-4bd5-4271-a94f-f93e99d6c8c0.png)

**Comment by yesoreyeram** [comment]
Shouldn't be problem.  How you are adding the api key in the URL ? ( via config/ query params?/direct?)   I would suggest couple of ways to debug.

* See browser console for any obvious errors
* Paste data directly inline mode ( to eliminate the possibility of parsing errors )
* Try the URL as is in query editor URL. ( create a new datasource instance without additional configuration , and then in the query directly paste the URL to eliminate potential configuration issues )

**Comment by wurongronga** [comment]
got the same problem here. I created a datasource without additional configuration, and add csrf token into the url header options. From the browser console I got the 401 and 500 errors
`{status: 500, statusText: 'Internal Server Error', data: {…}, config: {…}}
config: {method: 'POST', url: 'api/datasources/10/resources/proxy', data: {…}, retry: 0, headers: {…}, …}
data: {message: '401 Unauthorized\n', error: 'Internal Server Error', response: '401 Unauthorized\n'}
message: "401 Unauthorized\n"
status: 500
statusText: "Internal Server Error"`
btw, is possible to using cookies?

**Comment by pinou63** [comment]
Somebody to help us ???
Please :)

**Comment by yesoreyeram** [comment]
I am not sure whats going on and hard to debug with assumptions about your environment and setup.. I released 0.8.5 with explicit apiKey type authentication. Can you test with that if helps? That also give you `curl` like commands in query inspector.

**Comment by pinou63** [comment]
Hello and thank you for your response.
I just try and it works perfectly now with the version 0.8.3

Thanks for your help!

Y.
