### ISSUE TITLE
[Bug] Plugin not working in RedHat 7.9 (Plugin unavailable)

### ISSUE THREAD

**Issue by jtorkkel** [yesoreyeram/grafana-infinity-datasource#273]
**Describe the bug**
Adding the infinity datasource result saving error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/19704268/156384540-b87e2368-bc09-463a-9e27-f1568ef5694f.png)

** Details**
Plugin can be used from panels but 
A) default JSON URL query fails https://jsonplaceholder.typicode.com/users

{"status":500,"statusText":"Internal Server Error","data":{"message":"Metric request error"},"config":{"url":"api/ds/query","method":"POST","data":{"queries":[{"refId":"A","datasource":{"uid":"Hq68vHLnk","type":"yesoreyeram-infinity-datasource"},"type":"json","source":"url","format":"table","url":"https://jsonplaceholder.typicode.com/users","url_options":{"method":"GET","data":""},"root_selector":"","columns":[],"filters":[],"global_query_id":"","datasourceId":34,"intervalMs":5000,"maxDataPoints":2981}],"range":{"from":"2022-03-02T08:47:44.290Z","to":"2022-03-02T14:47:44.290Z","raw":{"from":"now-6h","to":"now"}},"from":"1646210864290","to":"1646232464290"},"requestId":"Q174","retry":0,"headers":{"X-Grafana-Org-Id":1},"hideFromInspector":false},"message":"Metric request error"}

- JSON inlile query fails 
{
"__name__": "job_teamname_app:system_cpu_usage:count",
"dnsname": "xxx-monitor-v1",
"job": "prod"
}

{"status":500,"statusText":"Internal Server Error","data":{"message":"Metric request error"},"config":{"url":"api/ds/query","method":"POST","data":{"queries":[{"refId":"A","datasource":{"uid":"Hq68vHLnk","type":"yesoreyeram-infinity-datasource"},"type":"json","source":"inline","format":"table","url":"https://jsonplaceholder.typicode.com/users","url_options":{"method":"GET","data":""},"root_selector":"","columns":[],"filters":[],"global_query_id":"","data":"{\n\"__name__\": \"job_teamname_app:system_cpu_usage:count\",\n\"dnsname\": \"xxx-monitor-v1\",\n\"job\": \"prod\"\n}","datasourceId":34,"intervalMs":5000,"maxDataPoints":2981}],"range":{"from":"2022-03-02T08:49:28.779Z","to":"2022-03-02T14:49:28.779Z","raw":{"from":"now-6h","to":"now"}},"from":"1646210968779","to":"1646232568779"},"requestId":"Q180","retry":0,"headers":{"X-Grafana-Org-Id":1},"hideFromInspector":false},"message":"Metric request error"} 

**Version Details:**

- Grafana version : 8.3.4
- Plugin version : 0.8.3

**Additional context**
In Windows10 Grafana 8.4.2 and Plugin 0.8.3 works

**Comment by yesoreyeram** [comment]
Does the previous version of the plugin used to work in RH for you?

**Comment by jtorkkel** [comment]
I have not tried that. Which version I should try ?
I have also Grafana 7.5.7 in one another Redhat machine --> can try if 0.8.3 works in that.

**Comment by jtorkkel** [comment]
Still fails in Grafana 8.4.2 or when plugin downgraded to (0.8.0, lower does not have Node Graph).

Zabbix had similar error when plugin was not compiled to bsd. But Redhad should work with linux_amd64.
https://github.com/alexanderzobnin/grafana-zabbix/issues/1054

**Comment by jtorkkel** [comment]
lvl=eror msg="Could not start plugin" pluginId=yesoreyeram-infinity-datasource err="fork/exec /var/lib/grafana/plugins/yesoreyeram-infini
ty-datasource/gpx_infinity_linux_amd64: permission denied"

Giving more permissions solved the issue
