### ISSUE TITLE
I can not create an alert with infinity data source

### ISSUE THREAD

**Issue by mahmutefe** [yesoreyeram/grafana-infinity-datasource#282]
Hi,

Firstly many thanks for providing the infinity plugin to us. I am trying to create an alert via the infinity data source. and  I am receiving the below error. I tried everything to pass this error. But, I could not. Is there a bug?

Sample API is: [https://thingspeak.com/channels/38629/feed.json](https://thingspeak.com/channels/38629/feed.json)

![image](https://user-images.githubusercontent.com/5229401/158916408-6c2276bb-1193-4588-a2a9-8b2d0c3f72ea.png)

**Comment by yesoreyeram** [comment]
Nope. Alerts not supported by the datasource
