### ISSUE TITLE
[Bug] Unable to query JSON from URL

### ISSUE THREAD

**Issue by BriannaBrown-hub** [yesoreyeram/grafana-infinity-datasource#290]
**Describe the bug**
I am attempting to return `JSON` from a `URL` in the `Table` format but the query is returning a 400. When I hit this endpoint from postman or curl, I am getting a 200 back as well as the expected json results. 

![image](https://user-images.githubusercontent.com/46937658/160025212-1096e00c-031e-492f-b630-f427013528ed.png)

When I check out the `Query Inspector` there is no error that appears.
![image](https://user-images.githubusercontent.com/46937658/160024660-c6849d4e-7a6b-4c46-a94b-f9beae608359.png)

Here is the response message from `inspect` under the `Response` tab:
```
{
   "results":{
      "A":{
         "frames":[
            {
               "schema":{
                  "name":"A",
                  "refId":"A",
                  "meta":{
                     "custom":{
                        "data":null,
                        "duration":12284751,
                        "error":"400 BAD REQUEST",
                        "query":{
                           "alias":"",
                           "columns":[
                              
                           ],
                           "csv_options":{
                              "columns":"",
                              "comment":"",
                              "delimiter":",",
                              "relax_column_count":false,
                              "skip_empty_lines":false,
                              "skip_lines_with_error":false
                           },
                           "data":"",
                           "expression":"",
                           "filters":[
                              
                           ],
                           "format":"table",
                           "global_query_id":"",
                           "groq":"",
                           "json_options":{
                              "columnar":false,
                              "root_is_not_array":false
                           },
                           "query_mode":"",
                           "refId":"A",
                           "root_selector":"",
                           "seriesCount":0,
                           "source":"url",
                           "type":"json",
                           "uql":"",
                           "url":"https://api.infisense.com/device/?keys=user_context\u0026partial=true\u0026include_gateways=true\u0026return_type=json-record",
                           "url_options":{
                              "data":"",
                              "headers":[
                                 {
                                    "key":"X-API-KEY",
                                    "value":"*********************"
                                 }
                              ],
                              "method":"GET",
                              "params":[
                                 
                              ]
                           }
                        },
                        "responseCodeFromServer":400
                     },
                     "executedQueryString":"https://api.infisense.com/device/?keys=user_context\u0026partial=true\u0026include_gateways=true\u0026return_type=json-record"
                  },
                  "fields":[
                     
                  ]
               },
               "data":{
                  "values":[
                     
                  ]
               }
            }
         ]
      }
   }
}
```

Here is a successful query with the signature information:

![image](https://user-images.githubusercontent.com/46937658/160025048-941ddc81-8373-46ae-9026-6802393a8cc9.png)
![image](https://user-images.githubusercontent.com/46937658/160025094-529469ba-e5ce-4c03-b821-ca3077ca89d7.png)

**Version Details:**

- Grafana version : 8.4.4
- Plugin version : 0.8.3

**Additional context**
The URL is hitting a Flask RESTX project. I am able to hit some api endpoints successfully and yield results from this project but not others.

**Comment by robianson** [comment]
@yesoreyeram wondering if you've managed to get eyes on this? We're a little stumped. The plugin is able to retrieve JSON data from some endpoints in our project but not others. The text of the response parses if we paste it in inline, but when try to retrieve from the URL we get a 400 error.

**Comment by yesoreyeram** [comment]
If only some URLs are not working, it is hard to tell. It is also hard to reproduce for me.

Typically this may happen when there is a URL configured in the datasource config. Try removing the URL in the datasource config and provide full URL in the query editor. Or create a new datasource instance without URL.

**Comment by yesoreyeram** [comment]
Also check the executed query string for more details. 0.8.8 have more error logs introduced . Give a try

**Comment by yesoreyeram** [comment]
I am closing this since this is very much URL specific and I am not able to reproduce.
