### ISSUE TITLE
[Bug] CRLF in UQL query window

### ISSUE THREAD

**Issue by kgroshert** [yesoreyeram/grafana-infinity-datasource#292]
**Describe the bug**
When I try to write a multiline UQL query and I press enter to write a second line (like in the examples) I get a "error applying uql query" message.

I looked at the dashboard-JSON and it looks like that:

`"uql": "parse-json\r\n| count"`

When I look at the demo-dashboards at herokuapp there is only "\n" in the query and it works. Not sure if this is something I can tune in my local Grafana installation or it has to be fixed in the plugin.

**Version Details:**

- Grafana version : 8.4.2
- Plugin version : 0.8.5

**Comment by yesoreyeram** [comment]
BTW, you edit the query in a windows machine?  If removing `\r` works, then definitely an issue with the UQL syntax. I doubt https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/289 also because of the same reason. ( cc @gdiana to confirm )

Fix coming in next version for `\r` escape characters.

**Comment by kgroshert** [comment]
Yes it's on a windows machine.

**Comment by kgroshert** [comment]
I removed the \r in the JSON but it did not help. I will try to find out whats different in the panels and report back.

**Comment by kgroshert** [comment]
Ok I think it was a caching-problem in Grafana. I created 2 identical panels, exported the JSON, removed the \r and then reimported the dashboard: Success. So it was the \r 👍

**Comment by gdiana** [comment]
Great and yes the caching does create problems and it appears the \r is just a niggle issue but which can create havoc :)

In my case I edited on MAC and saved and it works fine on MAC and Windows so it must be something simple ie \r

**Comment by yesoreyeram** [comment]
Fixed this in version 0.8.6. You can download from github releases page and soon it will be available in grafana catalog.

Feel free to reopen if the issue exists.
