### ISSUE TITLE
[Bug] The format as a number can not use negative numbers.

### ISSUE THREAD

**Issue by bighb69738** [yesoreyeram/grafana-infinity-datasource#297]
**Describe the bug**
The string value was negative number, but i tried to use the format as a number it will change to the positive number.

**Screenshots**
<img width="1023" alt="截圖 2022-04-07 下午3 47 17" src="https://user-images.githubusercontent.com/38970513/162148988-dfbf2730-f5f0-421b-9a58-61be529ab90c.png">
<img width="1031" alt="截圖 2022-04-07 下午3 47 26" src="https://user-images.githubusercontent.com/38970513/162148997-2632b28b-67f9-4f96-91fa-f1b9eb1427e1.png">

**Version Details:**
- Grafana version : 8.1.5
- Plugin version :0.8.3

**Comment by yesoreyeram** [comment]
I can confirm the bug. Fix coming in next release.
