### ISSUE TITLE
[Bug] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb032f6]

### ISSUE THREAD

**Issue by teturou8001** [yesoreyeram/grafana-infinity-datasource#299]
**Describe the bug**
I'm trying to evaluate Infinity DS on Grafana/K8s environment with some combinations like below, but all showed me the crash stack at Grafana logs.

Grafana 8.4.3 / Infinity 0.8.3 / SLES 15.1
Grafana 8.4.3 / Infinity 0.8.6 / SLES 15.1
Grafana 8.4.6 / Infinity 0.8.3 / SLES 15.1
Grafana 8.4.6 / Infinity 0.8.6 / SLES 15.1

**Screenshots**
![image](https://user-images.githubusercontent.com/31199772/163365729-641b1f86-3aca-4521-8582-5720fb0cda6e.png)

**Version Details:**

- Grafana version : Please see the above version combinations.
- Plugin version : Please see the above version combinations.

**Additional context**
I've also configured OAuth2 and it was configured at the helm like below.
![image](https://user-images.githubusercontent.com/31199772/163367069-a4394f52-e053-40f0-b2fa-e4bf0129e4cd.png)

**Comment by yesoreyeram** [comment]
Can you check 0.8.7 version? Above issue should go away with that.

**Comment by teturou8001** [comment]
Hi @yesoreyeram,
Thanks a lot for your quick fix! Now the crash has been resolved.
But, I still could not see any data with the inputs at Explorer for the default URL.
![image](https://user-images.githubusercontent.com/31199772/163515699-1e32182a-755d-4956-8e69-e14babbe94f2.png)

And, I cannot see any relevant logs in Grafana even though I've set the trace level to 'debug'.
Is there any way to check the reason?

**Comment by teturou8001** [comment]
Hi @yesoreyeram,

Can you add 'err' into any logs since 'err' should not be nil and it should contain some more details.

```
87     if err != nil && res == nil {  <-- err should not be null, then it'd be great to have err written in the trace or the error message.
88         return nil, http.StatusInternalServerError, duration, fmt.Errorf("error getting response from %s", url)
89     }                                                                                                          
```

In Grafana with 'Chrome' developer tool, I've found the returned message like below. But, no err information was recorded.

```
{"results":{"A":{"frames":[{"schema":{"name":"A","refId":"A","meta":{"custom":{"data":null,"duration":1972715716,"error":"error getting response from https://api.***.com/abc***","query":{"alias":"","columns":[],"csv_options":{"columns":"","comment":"","delimiter":"","relax_column_count":false,"skip_empty_lines":false,"skip_lines_with_error":false},"data":"","expression":"","filters":[],"format":"table","global_query_id":"","groq":"","json_options":{"columnar":false,"root_is_not_array":false},"query_mode":"","refId":"A","root_selector":"","seriesCount":0,"source":"url","type":"json","uql":"","url":"https://api.***.com/abc***","url_options":{"data":"","headers":null,"method":"GET","params":[{"key":"names","value":"HDBMemoryUsed"}]}},"responseCodeFromServer":500},"executedQueryString":"###############\n## URL\n###############\n\nhttps://api.***.com/abc***\n\n###############\n## Curl Command\n###############\n\ncurl -X 'GET' -H 'Content-Type: application/json' 'https://api.***.com/abc***'"},"fields":[]},"data":{"values":[]}}]}}}
```

Thanks.

**Comment by teturou8001** [comment]
With the below config, it works well. So, now I assume there seems to be an issue in OAuth configuration and/or impl. somewhere.
![image](https://user-images.githubusercontent.com/31199772/163737430-e02adcd4-e301-4404-abe5-a35742f24780.png)

**Comment by yesoreyeram** [comment]
As the original issue is resolved, I am closing this issue. In the upcoming version 0.8.8, I am adding more logging to the backend and also yaml provisioning helper will be added to the datasource config.

BTW, does your datasource working If you configure OAuth manually in GUI. That will help to eliminate the provisioning errors.

**Comment by teturou8001** [comment]
Thanks again for your fix.
And, I've found an issue from my end, which was the escape char issue of the helm templating. Now it was fixed. Thanks!

**Comment by yesoreyeram** [comment]
> Thanks again for your fix. And, I've found an issue from my end, which was the escape char issue of the helm templating. Now it was fixed. Thanks!

Glad to know you found the issue and it is all working now. 

It will be useful for other if you can share how you use the oauth with infinity. ( if you are using any public api endpoints)

**Comment by teturou8001** [comment]
Let me think a way to share it.

BTW, would you also have a plan to support X.509 authentication? If so, I think it'd be helpful to support higher security standard / policy in some use cases.
