### ISSUE TITLE
API Results in scientific (exponential) notation are not rendered correctly as numbers

### ISSUE THREAD

**Issue by ebachman24** [yesoreyeram/grafana-infinity-datasource#301]
Numbers in exponential notation are not rendered correctly when formatting them as numbers.  Instead, the exponent is ignored and the value is brought across as a decimal.   Interestingly, when formatting as a string, the full number value is rendered instead of the exponential shorthand, but as a string.  (see “im_BitsPerSecond” and “im_SpeedIn” from the attached example.  --Example is using a time series dataset, formatted in JSON.

One would expect to see the exponential values rendered like…   _as Number: 10000000000   |   as String: 1.0E10_

![image](https://user-images.githubusercontent.com/104096952/164299151-00b34597-64b9-4c47-b315-c09455c85d19.png)

**Version Details:**

- Grafana version :  7.4.5
- Plugin version :  0.8.0

_tested on plugin version 0.8.7 as well_

**Additional context** --Side Note..
There _is_ a workaround to this on newer versions of Grafana.  Transformation-Convert field type can be used on the rendered string to bring it across as a number.  Though this is still an issue

**Comment by yesoreyeram** [comment]
I can confirm the bug. Fix coming soon.

**Comment by yesoreyeram** [comment]
This is now fixed in v0.8.8. Give a try!

**Comment by ebachman24** [comment]
Thanks!  I can confirm that it is working.
Also, as a side note, after you upgrade the plugin, be sure to log out and back in to see the changes take effect.
