### ISSUE TITLE
BTW, how do you achieve this with JSONata?

### ISSUE THREAD

**Issue by gdiana** [yesoreyeram/grafana-infinity-datasource#304]
yea.. splitting a string is not supported in UQL yet. But looks like an interesting usecase. Should easy to support in next few versions of UQL.  

BTW, how do you achieve this with JSONata?

_Originally posted by @yesoreyeram in https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/303#discussioncomment-2616716_

I simply did a URL call in the chrome browser, did a browser available XML to JSON conversion then used the free JSONATA editor  at https://try.jsonata.org/

**Comment by yesoreyeram** [comment]
i am interested to see the JSONta query

**Comment by gdiana** [comment]
I only used it to work out the path/scope and did not do any queries. But I am sure that any JSONATA queries should work with your UQL. I use it as GRAFANA provides very limited space to view data and query results. NODE-RED has same problem.

It is a great online JSONATA debugging tool and one can do quite complex queries, and reformatting but the learning curve is steep. it requires one to understand objects, arrays and scope which is a very grey area as far as various API XML providers go. What one can do depends on any API developer's understanding or deliberate limits on how the XML output may be "easily" reformatted.

I used it some time back to format the XML -> JSON and then format the JSON data as required by the NODE-RED GRAPH

I will go back and get the the XML example and query I used to do this. I will try it out with your UQL and see if i get same results.

Just a quick. you showed this in your example

parse-json
| scope "xml.meters.meter"
| extend "timeitems"="dailyreads.dailyread.vidata.timeitem"
| project-away "dailyreads"
| mv-expand "timeItem"="timeitems"
| extend "time"=todatetime("timeItem.time"), "red_i"="timeItem.red.i"
| project "time", "red_i", strcat("cid",'--',"serial")

Here you limited the scope to allow access to higher-level variables and then used extend to define the higher level downstream data. Then later you could use the upper level (cid and serial) and lower level data (time and red-i)

As much as I try to replicate this using your example it will not work
If I usee the full scope "xml.meters.meter.dailyreads.dailyread.vidata.timeitem" I can see all the lower level data but cannot access the upper data due to the extended scope.

So it appears we may define different levels of scope but why yours works and mine does not baffles me.

Is it possible to provide me the URL you used as the only difference is that I am using inline and have experienced some very weird browser behaviour where GRAFANA hangs? Maybe storage limits using INLINE?

Also if we go through each line of the query one by one should we see output at every line. I comment out the lines and then see what gets returned when I remove each comment.

many thanks

**Comment by yesoreyeram** [comment]
I assume this is no longer an issue. ( based on the other discussions around)

**Comment by gdiana** [comment]
No, but what interests me is how it worked and why? Can do same with jsonata.

Cheers

Greg Diana

**Comment by CloudLearner2023** [comment]
I am new to json and uql. Could u help me to get count of sub = hindi and res = pass using uql please. Below is the example json: 
[{
"class" : "6t",
"scorecard": [{
"Name": "abc",
"Sub": "hindi",
"Res": "pass"
}],
"class": "7t",
"scorecard": [{
"Name": "def",
"Sub": "hindi",
"Res": "pass"
}],
"class": "8t",
"scorecard": [{
"Name": "hij",
"Sub": "hindi",
"Res": "fail"
}]
}]
