### ISSUE TITLE
Passing input in the URL to get last 2 hours data

### ISSUE THREAD

**Issue by manjunathnayaka22** [yesoreyeram/grafana-infinity-datasource#319]

**Comment by manjunathnayaka22** [comment]
Thank you. I have already tried choosing the time in the Grafana dashbaord, but it keep shows the same data like past 12 days of old data. Looking forward to get a solution on this. Thanks

**Comment by yesoreyeram** [comment]
Can you check query inspector about what URL is being passed? Then manually curl the URL outside grafana if that returns correct data

**Comment by manjunathnayaka22** [comment]
Hi Sriram, you can close this issue out. I am able to fix the issue by modifying the date and time syntax. I have changed from lower case to upper case as per this document. 
https://momentjs.com/docs/#/displaying/

**Comment by yesoreyeram** [comment]
I don't have access to your API. You can debug further by manually calling the API via curl and see if time filter works outside grafana and then make sure you see the same URL format in grafana query inspector.
