### ISSUE TITLE
[Bug] Query field disappeared when creating variable

### ISSUE THREAD

**Issue by jokerfvd** [yesoreyeram/grafana-infinity-datasource#39]
**Describe the bug**
The query field disappeared in the variables creation 

**Screenshots**
![image](https://user-images.githubusercontent.com/2172117/108549797-6f3b8a80-72cc-11eb-8722-a0852f4d16fa.png)

**Version Details:**
 - Grafana version : 6.7.1
 - Plugin version : Release v0.6.0

**Additional context**
In the release 0.5.0 of the plugin worked fine.
In Grafana version 7.4.2 it works fine as show bellow
![image](https://user-images.githubusercontent.com/2172117/108551302-84b1b400-72ce-11eb-9c98-3da0e1acafce.png)

**Comment by yesoreyeram** [comment]
the equivalent is now `query` field under the `query type` row. 

These changes required for the plugin to add advanced options. ( rather than having everything in a string , give rich gui. ).

**Comment by jokerfvd** [comment]
In Grafana version : 6.7.1 don't have the query field.
The bug is in the first image I showed.
The second image shows in Grafana version 7.4.2 . In this version it's OK

**Comment by yesoreyeram** [comment]
I haven't tested on Grafana 6.x version. Fix for grafana 6.x can be done but will introduce additional complexity maintaining the plugin going forward. 

The workaround is stick with older plugin release (you can download release page. Probably 6.0.0-alpha1 version ). Thanks for reporting the issue and sorry for inconvenience. I am closing the bug as `can't fix now` to reduce the complexity. Feel free to propose any solution that works for you.
