### ISSUE TITLE
Hope it can support timestamp in nanoseconds format.

### ISSUE THREAD

**Issue by jylsec** [yesoreyeram/grafana-infinity-datasource#459]
### Discussed in https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/458

<div type='discussions-op-text'>

<sup>Originally posted by **jylsec** November 13, 2022</sup>
Infinity is a really powerful plugin.But I found it only support three kinds of timestamps.
EdgeX Foundry(A platform) API only return  timestamp in nanoseconds format.
So I think Infinity will be more powerful if it support  Unix ns.</div>

**Comment by yosiasz** [comment]
have you looked at this function in UQL 

```
unixtime_nanoseconds_todatetime("dob")
```

**Comment by jylsec** [comment]
Thanks.Perfect Plugin!

> have you looked at this function in UQL
> 
> ```
> unixtime_nanoseconds_todatetime("dob")
> ```
