### ISSUE TITLE
[Bug] Variables are not resolved properly in the query

### ISSUE THREAD

**Issue by magaton** [yesoreyeram/grafana-infinity-datasource#48]
**Describe the bug**
Variables are not resolved properly in the query. There are 2 problems that  I see.
1. If the Variable is of type String, then the query: 
`query { 
pqv(logins: ["${__user.login}"], periods:$periods){
   name 
   value
    data
  }
}
`
will fail because period is not the number (it contains letters).
The only solution I found is to wrap periods in double quotes, like I did with ${__user.login}, but this then won't work with arrays.

The other problem is: The multi-select will be wrapped in {}, not in []

I tried to specify array myself in the query:
`query { 
pqv(logins: ["${__user.login}"], periods:[$periods]){
   name 
   value
    data
  }
}
`

**Screenshots**
<img width="1656" alt="Screenshot 2021-03-08 at 13 17 10" src="https://user-images.githubusercontent.com/4103157/110320877-395b0d80-8011-11eb-96b7-e984f66302bf.png">

**Version Details:**
 - Grafana version : 7.3.5
 - Plugin version : 0.6.0 latest

**Additional context**

**Comment by magaton** [comment]
The same problems (number vs string and incorrectly generated parenthesis for array) happen If the variable is of type Custom instead of Query.

**Comment by magaton** [comment]
Were you able to reproduce it or you need some additional info?

**Comment by yesoreyeram** [comment]
Hi @magaton i don't think it is really a plugin issue. Have u tried the options specified here https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/ ?

**Comment by magaton** [comment]
Wow, I did not know that. Thank you very much!
