### ISSUE TITLE
[Feature Request] multi root support for xml

### ISSUE THREAD

**Issue by gdiana** [yesoreyeram/grafana-infinity-datasource#52]
Hi,  
I am using the infinity datasource and in particular the XML datasource.

The issue I am having is that the XML source has various levels and I wish to be able to create a single table consisting of variables' at different levels or xmlpaths

Currently, one may only define a single Rows/Root (xmlpath) to any desired level and create a Table. However, one is not able to include any other data or variables from any other level. 

One may make another query using another path but then one is left with two separate tables which one is unable to join.

As such it would be great if you could include the ability to allow several Rows/Root or xml paths within a single query to allow variables at various nested level using separate xmlpaths so that one may construct a table from any level and not just restricted to a single table per path as is currently the case.

<xml>
      <result>SUCCESS</result>
      <startdate>2021-03-01 00:00:00.000</startdate>
      <date>2021-03-22 21:00:00.000</date>
                <meters>
                        <meter>
                             <e1>1301428.2108549944</e1>
                             <e1status>1</e1status>
                             <e1rdate>2021-03-22 21:00:00.000</e1rdate>
                       </meter>
                <meters>
<xml>

So now we can do as follows

xml.result
   selector  startdate ...................
   selector date....................
xml.meters[0].meter
   selector e1 ...........................
   selector e1status .........

In this way and with this feature one may "pick and choose" data from several levels and construct a single table and I am sure this will also apply to the JSON.

One may then use the transform to correctly organize the fields and which cannot be done when using multiple tables.

Kind regards

Greg Diana

**Comment by yesoreyeram** [comment]
Hi @gdiana  i don't think that is possible. Introducing those kind of feature may not be very common usecase. Also that may introduce additional complexity to maintain the plugin. Btw, thanks for the feedback. Any XML example is much appreciated.( I couldn't understand the exact use case )

**Comment by gdiana** [comment]
Hi,
The use is for nested tables where one uses different layers for
different levels of the nested table.
So for example, if one queries data from several meters one does not have
to repeat the name location etc for each line of the meter data returned.

Or one may have several sites each with several meters and each meter with
a range of data between two dates.

Very commonly used. To do this using xml one has to use different levels.

[image: image.png]

Kind regards


Gregory Diana
_______________________________________


22 Glen Grove
Glenwood
Durban 4001

Phone(h&w):031-2616761 (h)
*Fax2Email: 086 474 3450*
Cell: 0784515277
E-mail: ***@***.***
E-mail: ***@***.*** ***@***.***>
Skype: gregory.diana
Print: ***@***.***

**Comment by billabongrob** [comment]
This would be an example from NMAP scan output, may not be the best example, but a common one nonetheless....

```
<host starttime="1648667798" endtime="1648667800">
    <status state="up" reason="conn-refused" reason_ttl="0"/>
    <address addr="10.24.130.1" addrtype="ipv4"/>
    <hostnames>
    </hostnames>
        <ports>
            <port protocol="tcp" portid="1521">
            <state state="filtered" reason="no-response" reason_ttl="0"/>
            <service name="oracle" method="table" conf="3"/>
            </port>
        </ports>
    <times srtt="472" rttvar="5000" to="100000"/>
</host>
```

**Comment by yesoreyeram** [comment]
@gdiana / @billabongrob  - Have you tried UQL ? I believe you can achieve this with UQL.  Example  [query](https://grafana-infinity-datasource.herokuapp.com/explore?orgId=1&left=%7B%22datasource%22:%22Infinity%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22type%22:%22uql%22,%22source%22:%22inline%22,%22format%22:%22table%22,%22url%22:%22https:%2F%2Fapi-eu.livepool.io%2Fapi%2Fv1%2Ftranscoders%22,%22url_options%22:%7B%22method%22:%22GET%22,%22data%22:%22%22%7D,%22root_selector%22:%22%22,%22columns%22:%5B%5D,%22filters%22:%5B%5D,%22global_query_id%22:%22%22,%22uql%22:%22parse-xml%5Cn%23%20%7C%20scope%20%5C%22nmapresult.hosts.host%5C%22%5Cn%23%20%7C%20project%20%5C%22host%5C%22%3D%5C%22@_name%5C%22,%20%5C%22ports%5C%22%3D%5C%22ports.port%5C%22%5Cn%23%20%7C%20mv-expand%20%5C%22port%5C%22%3D%5C%22ports%5C%22%5Cn%23%20%7C%20project%20%5C%22host%5C%22%3D%5C%22host%5C%22,%20%5C%22portName%5C%22%3D%5C%22port.@_name%5C%22,%20%5C%22port%5C%22%3D%5C%22port.%23text%5C%22%5Cn%23%20%7C%20summarize%20%5C%22ports_count%5C%22%3Dcount()%20by%20%5C%22port%5C%22%5Cn%23%20%7C%20order%20by%20%5C%22ports_count%5C%22%20desc%5Cn%22,%22data%22:%22%3Cnmapresult%3E%5Cn%3Chosts%3E%5Cn%20%20%20%20%3Chost%20name%3D%5C%22host1%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cports%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cport%20name%3D%5C%22http%5C%22%3E80%3C%2Fport%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cport%20name%3D%5C%22https%5C%22%3E443%3C%2Fport%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fports%3E%5Cn%20%20%20%20%20%3C%2Fhost%3E%5Cn%20%20%20%20%3Chost%20name%3D%5C%22host2%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cports%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cport%20name%3D%5C%22http%5C%22%3E80%3C%2Fport%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cport%20name%3D%5C%22ssh%5C%22%3E22%3C%2Fport%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fports%3E%5Cn%20%20%20%20%3C%2Fhost%3E%5Cn%3C%2Fhosts%3E%5Cn%3C%2Fnmapresult%3E%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D).

```xml
<nmapresult>
<hosts>
    <host name="host1">
        <ports>
            <port name="http">80</port>
            <port name="https">443</port>
        </ports>
     </host>
    <host name="host2">
        <ports>
            <port name="http">80</port>
            <port name="ssh">22</port>
        </ports>
    </host>
</hosts>
</nmapresult>
```
```kusto
parse-xml
| scope "nmapresult.hosts.host"
| project "host"="@_name", "ports"="ports.port"
| mv-expand "port"="ports"
| project "host"="host", "portName"="port.@_name", "port"="port.#text"
```

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/153843/164216034-230a4bc2-963e-4115-88eb-e0651846312c.png">

PS: support multi root for xml was bit hard. So took an alternative approach via UQL . Let me know if that works for you.

**Comment by gdiana** [comment]
Hi,

Yes I am using it and it is working fine so far.

I have some complex XML trees where neither XML or UQL are working which I am working on.

I use JSONATA (  https://try.jsonata.org/ )to fathom out how the tree structure works and what works fine in JASONATA does not always work in XML or UQL.

The UQL aggregate functions are great and although it is early days it would be great to be able to nest order by so for example one may determine the monthly energy consumption for several years or week energy consumption per month or months, but I expect these will come in time.

I have found that when one does a UQL project that despite the order that one uses in the query the actual order in the resulting table seems to be calculation time-dependent, so using a mul() for exaple will cause the second item to appear as the last table column and not second.

Thnaks for everything it is great.

**Comment by yesoreyeram** [comment]
> I have some complex XML trees where neither XML or UQL are working which I am working on.

Can you post an example and what you are trying to achieve with that. I will try my best.

> The UQL aggregate functions are great and although it is early days it would be great to be able to nest order by so for example one may determine the monthly energy consumption for several years or week energy consumption per month or months, but I expect these will come in time.

I think it is already possible somehow,  but interested to see an example data and what you are trying to achieve. 

Again, Thanks for the kind words and contribution.
