### ISSUE TITLE
Version0.7 Alpha0 not loading in grafana

### ISSUE THREAD

**Issue by gdiana** [yesoreyeram/grafana-infinity-datasource#53]
Hi,

I downloaded the new version and installed, but when I tried to use no infinity datasource was available in the menu?

I removed V7 and replaced with V6 and all was ok. 

Just for your info as it is still in beta.

Cheers

Greg Diana

**Comment by yesoreyeram** [comment]
Thanks @gdiana for notifying. I will have a look. I am migrating the plugin into back end plugin to support more features. Might be issue with signing.

**Comment by yesoreyeram** [comment]
Btw, what version of grafana you are using?

**Comment by gdiana** [comment]
I am using the latest version. Sorry I am off the grid so cannot confirm version number but it is 7.?
Cheers


Sent from my iPhone

On 27 Mar 2021, at 23:56, Sriram ***@***.***> wrote:

﻿
Btw, what version of grafana you are using?

**Comment by gdiana** [comment]
[image: image.png]

Kind reegards


Gregory Diana
_______________________________________


22 Glen Grove
Glenwood
Durban 4001

Phone(h&w):031-2616761 (h)
*Fax2Email: 086 474 3450*
Cell: 0784515277
E-mail: ***@***.***
E-mail: ***@***.*** ***@***.***>
Skype: gregory.diana
Print: ***@***.***

**Comment by yesoreyeram** [comment]
@gdiana can you confirm grafana version and os it is running. Sorry your screenshot is missing.

**Comment by gdiana** [comment]
Sorry, ver 7.5.1

[image: image.png]

Also, note that one may use the CONCATENATE transform function to join the
table queries from different XML, JSON levels. I have not tried it but saw
this elsewhere, but it is far from any true nested table from any BI tool
such MSSQL Designer fro eg.

**Comment by gdiana** [comment]
Ok, I tried the latest version and it worked fine no problems.

Cheers

Greg Dian a

**Comment by yesoreyeram** [comment]
@gdiana - How did you install the plugin? which url you used to download?

I have tested with

```sh
docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.0-alpha1/yesoreyeram-infinity-datasource-0.7.0.zip;yesoreyeram-infinity-datasource" grafana/grafana:7.5.3
```

Feel free to reopen the issue if exists

**Comment by gdiana** [comment]
I just went and downloaded as you suggested. Copied to directory. Restarted Grafana and all worked fine. 

Sent from my iPhone

On 27 Apr 2021, at 07:50, Sriram ***@***.***> wrote:

﻿
@gdiana - How did you install the plugin? which url you used to download?

I have tested with

docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.0-alpha1/yesoreyeram-infinity-datasource-0.7.0.zip;yesoreyeram-infinity-datasource" grafana/grafana:7.5.3
Feel free to reopen the issue if exists
