### ISSUE TITLE
Adding data source throws "Unexpected token '<' while evaluating plugin"

### ISSUE THREAD

**Issue by stansotn** [yesoreyeram/grafana-infinity-datasource#6]
**Describe the bug**
Adding a new data source throws the following error. 
```
Unexpected token '<' Evaluating http://localhost:3000/public/plugins/yesoreyeram-infinity-datasource/module.js Loading plugins/yesoreyeram-infinity-datasource/module
Data Source Error
```

**How To Reproduce**
1. Clean grafana install on ubuntu 20.04 raspi4.
```
sudo apt install grafana
service grafana-server start
```
2. Install the plugin
```
sudo grafana-cli --pluginUrl https://github.com/yesoreyeram/grafana-infinity-datasource/archive/master.zip plugins install yesoreyeram-infinity-datasource
service grafana-server restart
```
3. Add infinity data source.

**Version Details:**
 - Grafana version : v.7.3.3
 - Plugin version : c.0.6.0

**Additional context**
After throwing the error, grafana adds a placeholder for the infinity data source, which is impossible to delete `Missing valid data source id`, olny `sudo apt purge grafana` deletes the broken placeholders=(

**Comment by yesoreyeram** [comment]
Can u try with the updated zip url from release page?

**Comment by stansotn** [comment]
Everything works after downloading the last release and manually copying to grafana's plugins folder. Worth updating tutorial?

**Comment by yesoreyeram** [comment]
Then,  I think your JSON/CSV might be blocked from downloading using CORS rule i guess.

**Comment by stansotn** [comment]
Hmm.. I looked into the api server that I would like to pull the data from and it never receives http request from grafana.. Any clues?

**Comment by yesoreyeram** [comment]
Check if your API server is protected by CORS rule. That may be the reason

**Comment by stansotn** [comment]
I made sure CORS and CSRF are disabled, my api server is a simple flask-restful app returning json strings like
```
[
    {
        "product_id": 4,
        "product_name": "Awesome"
    },
    {
        "product_id": 100,
        "product_name": "Unicorn"
    }
]
```

**Comment by chlarsen** [comment]
Exactly the same issues here, running Grafana 6.18. Definitely no cross-scripting issue.
`Unexpected token '<' Evaluating http://localhost:3000/public/plugins/yesoreyeram-infinity-datasource/module.js Loading plugins/yesoreyeram-infinity-datasource/module
Data Source Error`
As this plugin looks like taking a fantastic route, amy help would be hugely appreciated.

**Comment by yesoreyeram** [comment]
ok. got it. in case if you are downloading directly the master branch you might get the error. Current master doesn't include the dist folder. As per the recent guidelines regarding the grafana plugins, i have removed the dist folder from master. So try downloading from the release page. Try and let me know.

https://github.com/yesoreyeram/grafana-infinity-datasource/releases

and of course doucment needs update. Good luck.

**Comment by chlarsen** [comment]
Thank you, but I did try this, after looking at the above conversation. Here is what happens after unzipping the latest asset, and restarting grafana:
Clicking in the properly displayed plugin creates a loop.
If I go back, a new data source option can be found; your infinity data source.
Upon clicking on the latter, the above error re-appears, as described in the heading.
Summary: This is not helping, as already outlined by someone else above.
Sorry!

**Comment by yesoreyeram** [comment]
@chlarsen - sorry that you are having trouble. Which version of grafana you are using? As I mentioned previously, grafana 7+ only tested and supported.

**Comment by chlarsen** [comment]
The error refers to version 7.3.4, and reflects exactly the same experience as reported before by others, I am afraid. 
Thank you!

**Comment by chlarsen** [comment]
I have attempted all possible installation methods, via documentation, assets, master.zip, and they ALL produce exactly the same error as described in the heading. Please re-open this issue and file it as bug.

**Comment by stansotn** [comment]
Yep, I unpacked the newest release from https://github.com/yesoreyeram/grafana-infinity-datasource/releases and still get the same behavior.

**Comment by yesoreyeram** [comment]
If you are still getting this error, feel free to reopen the bug.
