### ISSUE TITLE
[Feature Request] Token authentication

### ISSUE THREAD

**Issue by edias88** [yesoreyeram/grafana-infinity-datasource#7]
Hi, 
I started to test your plugin and I think its very useful plugin for my usecase. I wanted to configure an advanced auhtenication and I ran into some problems and I hope that can you help me with that.

I'm trying to configure a token auhthentication for the datasource, but I'm not sure where to start.

In order to connect to the rest api I need to first get a token from a url( authentication using basic auth) and then I can use this token in my requests. When I authenticate I get a response as given here below

{"idSysteme":"TMP","codeSysteme":null,"errorCode":"200","errorMessage":"OK","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRNUCIsIm5iZiI6MTYwNjgyOTgyOSwiZXhwIjoxNjA2ODMzNDI5LCJpYXQiOjE2MDY4Mjk4Mjl9.XqaTkQ2TuFOokPiSY1UNlfMjBJ_jjpqVzTnih5ZwSh4"}

I need to parse this token and pass it as bearer token in my request Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRNUCIsIm5iZiI6MTYwNjgyOTgyOSwiZXhwIjoxNjA2ODMzNDI5LCJpYXQiOjE2MDY4Mjk4Mjl9.XqaTkQ2TuFOokPiSY1UNlfMjBJ_jjpqVzTnih5ZwSh4

Could you please tell me if this is possible?

Thanks in advance.

Best regards,
Emanuel

**Comment by yesoreyeram** [comment]
Hi Emanuel. Currently token authentication is not supported also not in immediate roadmap.

**Comment by edias88** [comment]
Hi Sriram,

Thank you for your response.

Best regards,

Emanuel

**Comment by yesoreyeram** [comment]
Work for token authentication started at [a feature branch](https://github.com/yesoreyeram/grafana-infinity-datasource/tree/feature/token-authentication). If successful, it may land in 0.7.0 version.  Draft doc available in discussion #40 
 
@Na-ru-to4170 - In case if you struggling with the implementation, Try the branch I created and test.

**Comment by n4l-tony** [comment]
> Work for token authentication started at [a feature branch](https://github.com/yesoreyeram/grafana-infinity-datasource/tree/feature/token-authentication). If successful, it may land in 0.7.0 version. Draft doc available in discussion #40
> 
> @Na-ru-to4170 - In case if you struggling with the implementation, Try the branch I created and test.
Hey yesoreram, just tied bearer token authentication in v0.7.0, it still doesn't work, no data output.

**Comment by rksawyer** [comment]
Any plans to revisit Token Authentication as a feature?

**Comment by yesoreyeram** [comment]
Recent version of the plugin 0.8.7 have support for multiple authentication methods including oauth client credentials.  Refer [authentication section ](https://yesoreyeram.github.io/grafana-infinity-datasource/wiki/authentication) of the documentation for more details.

If still doesn't work for you, share the api details in the discussion [here](https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/260)
