### ISSUE TITLE
[Feature Request] Additional CSV options

### ISSUE THREAD

**Issue by briend** [yesoreyeram/grafana-infinity-datasource#76]
**Is your feature request related to a problem? Please describe.**
The CSV file I have access to uses semicolons instead of commas and will not be trivial to change

**Describe the solution you'd like**
Add additional options such as delimiter, header row, etc.  Similar to another Grafana plugin that only does CSV: https://marcus.se.net/grafana-csv-datasource/query-editor

**Comment by yesoreyeram** [comment]
This is available in version 0.7.0-alpha4 .

To try this upcoming feature, use the below links

Download : https://github.com/yesoreyeram/grafana-infinity-datasource/releases/tag/v0.7.0-alpha4
Document : https://grafana-infinity-datasource-d0prt6c7w-yesoreyeram.vercel.app/

**Comment by yesoreyeram** [comment]
This is now available in master and released as v0.7. Download from https://grafana.com/plugins/yesoreyeram-infinity-datasource

**Comment by briend** [comment]
Awesome, seems to work great!  Thanks!
