### ISSUE TITLE
[Bug] Mixed Mode no longer works in 0.7.0

### ISSUE THREAD

**Issue by briend** [yesoreyeram/grafana-infinity-datasource#78]
**Describe the bug**
In Infinity `0.6.0` I was able to use Mixed mode for the Grafana Datasource. This is a great feature because I can combine the results of a CSV with a Prometheus query and use an `Outer Join` transformation to combine the datasets into one panel, adding extra fields that are missing from Prometheus. However, with Infinity `0.7.0` the Mixed mode does not work; the panel never refreshes. As soon as you change to `Mixed` mode the panel no longer refreshes even with just one datasource.

**Screenshots**

This works:

![image](https://user-images.githubusercontent.com/6015639/119392682-ea725b00-bc84-11eb-9819-ecf4ffbc9ee2.png)

But as soon as you change to `- Mixed -`, the panel does not load and just shows a spinning icon as if it is a long query:

![image](https://user-images.githubusercontent.com/6015639/119392735-fcec9480-bc84-11eb-9db6-fbf3afa9c328.png)

![image](https://user-images.githubusercontent.com/6015639/119393406-c19e9580-bc85-11eb-9178-9b31c810f703.png)

Query inspector never loads:

![image](https://user-images.githubusercontent.com/6015639/119393848-57d2bb80-bc86-11eb-88c9-a5166b5f45b4.png)

**Version Details:**

- Grafana version : Grafana v7.3.5, also tested Grafana v7.5.5
- Plugin version : 0.7.0

**Additional context**
Debug logs on Grafana did not show anything unusual:

```
t=2021-05-24T19:06:58+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=2 orgId=1
t=2021-05-24T19:07:02+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

**Comment by yesoreyeram** [comment]
Thanks @briend for reporting. Extremely sorry that you have trouble with the new version. This was missed when the migration to bknd happened. I can acknowledge the issue. Will work on fix once I am ready with that.

**Comment by yesoreyeram** [comment]
Fix is now available in master and in v0.7.1 https://github.com/yesoreyeram/grafana-infinity-datasource/releases/tag/v0.7.1

**Comment by yesoreyeram** [comment]
@briend - can you check if this works for you

**Comment by briend** [comment]
Seems to work great!  Thanks so much for the quick update!
