### ISSUE TITLE
[Bug] CSV Options panel for global query and dashboard variables does not work

### ISSUE THREAD

**Issue by briend** [yesoreyeram/grafana-infinity-datasource#79]
**Describe the bug**
Clicking on "CSV Options" from an Infinity dashboard variable does not open. As soon as you click it, you are taken back one screen to the Variables list. You might see the CSV Options panel appear for just a moment before being taken back to the Variables list.

**Screenshots**
![image](https://user-images.githubusercontent.com/6015639/119746084-74b4ed80-be44-11eb-930d-ba835aef2f0e.png)

**Version Details:**

- Grafana version : 7.3.5, 7.5.5
- Plugin version : 0.7.1
- Safari and Chrome browsers

**Additional context**
related: https://github.com/yesoreyeram/grafana-infinity-datasource/issues/76

**Comment by briend** [comment]
I also noticed the CSV Options don't quite work for the global queries

From a Global Query editor, the CSV Options panel does appear, however none of the fields are editable/active (cannot type in a new Delimiter)

![image](https://user-images.githubusercontent.com/6015639/119747549-d2970480-be47-11eb-8a18-b9456d4f29b1.png)

**Comment by yesoreyeram** [comment]
Unfortunately the variable editor is broken. Sorry to hear that you are having trouble. Related to #32 

Global query issue is something new i can see. Thanks for reporting this.

**Comment by yesoreyeram** [comment]
@briend - Have you check the recent versions and the above issues should have fixed in there. Let me know if you still have issues.
