### ISSUE TITLE
[Bug] Cannot add more than one column for JSON template variable

### ISSUE THREAD

**Issue by briend** [yesoreyeram/grafana-infinity-datasource#80]
**Describe the bug**
Using a Grafana Variable, I've setup a working JSON query that returns values for one column from my json file.  However if I try to add another column, I am immediately taken back to the Variables screen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6015639/119914765-d1cca400-bf15-11eb-9e22-e133675ae9a0.png)

**Version Details:**

- Grafana version : 7.3.5, 7.5.5
- Plugin version : 0.7.1

**Additional context**
I am trying to add the 2nd column so I can use the Results filter to only give me back one type of record. I'm not sure if that will be possible. It would be nice if I could filter on any fields without also returning that data.

**Comment by yesoreyeram** [comment]
Thanks for reporting this. Unfortunately the variable editor is broken. Sorry to hear that you are having trouble.  Related to #32

**Comment by psycholock13** [comment]
Thank you for response! Hope you can fix it :)
Just for additional info - I was upgrade to 0.7.2 - same problem.

**Comment by yesoreyeram** [comment]
This is fixed in v0.7.3 . Feel free to reopen if you see any odd behaviour.
