### ISSUE TITLE
[Bug] Big json payload fail with "503 Service Unavailable"

### ISSUE THREAD

**Issue by ckocyigit** [yesoreyeram/grafana-infinity-datasource#85]
**Describe the bug**
I have two json streams from a backend one is called info and one is called health. Both are reachable and working. Info has much less information than health. When using info there is no issues. Switching to health endpoint ends up with an error message :
![image](https://user-images.githubusercontent.com/60385015/121313140-649e1300-c906-11eb-918f-c6178d89a097.png)

**Version Details:**

- Grafana version : v7.5.7 (91de51771c)
- Plugin version : 0.7.0

**Comment by yesoreyeram** [comment]
Can you provide more information? like size of the payload , sample data to reproduce and grafana version

**Comment by ckocyigit** [comment]
The size of the payload is around 5.5K (health.json with ls -lh) 
Grafana version is v7.5.7 (91de51771c)
Unfortunately I can not give you any sample data.
It fails after some time it takes about 2-3 seconds buffering and then it fails with 503.
There is no useful output in the grafana docker logs too.
