### ISSUE TITLE
grammar error on website

### ISSUE THREAD

**Issue by jftuga** [yesoreyeram/grafana-infinity-datasource#89]
https://github.com/yesoreyeram/grafana-infinity-datasource/blob/d40f60cc998c6976e198a0e039a16c348ee8ead1/src/pages/index.tsx#L69

Should be this as JSON is listed twice:

     Visualize data from JSON, CSV, XML GraphQL, HTML &amp; REST APIs. Also turns any website into

**Comment by yesoreyeram** [comment]
Yeah good catch. You can send a pull request as well to fix this. Feel free to send pull request with fix. Thank you.

**Comment by yesoreyeram** [comment]
This is fixed now.
