### ISSUE TITLE
HTTP return code feature.

### ISSUE THREAD

**Issue by leoberbert** [yesoreyeram/grafana-infinity-datasource#9]
Dear Friend,

Would it be possible to implement the mapping of http codes for each query?

For example:

![image](https://user-images.githubusercontent.com/16724862/101082416-2d7f2b80-358a-11eb-95fc-3d50cf2a9e5c.png)

Its possible? As it currently only displays data that returns success, however when we have errors, only an error message is displayed on the panel.

![image](https://user-images.githubusercontent.com/16724862/101082877-f3faf000-358a-11eb-963c-e5671d3f7530.png)

Regards,

**Comment by yesoreyeram** [comment]
hi - Sorry missed the issue and sorry for the delay.

In recent versions (0.8.3+), You will see the error code in the message when the response code is not 200. Hope it helps. I don't think the plugin will be supporting the http response code as column anytime soon.
